
-- Enable Row Level Security
alter default privileges in schema public grant all on tables to postgres, anon, authenticated, service_role;

-- 1. LETTERS TABLE
create table letters (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  content text not null,
  era text default 'midnights', -- 'red', 'folklore', 'midnights', 'lover'
  cover_image text,
  author text default 'Saanvi'
);

-- 2. SONGS TABLE
create table songs (
  id bigint generated by default as identity primary key,
  added_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  artist text not null,
  cover_url text,
  preview_url text
);

-- 3. PROMISES TABLE
create table promises (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  description text not null,
  is_fulfilled boolean default false
);

-- Seed some initial data (Optional)
insert into letters (title, content, era, author) values 
('First Letter', 'This is our first letter in the new system.', 'red', 'Saanvi');

insert into songs (title, artist) values 
('Lover', 'Taylor Swift');

insert into promises (title, description) values 
('Always be there', 'No matter what happens, I will be there.');
